# Generated by Django 6.0.2 on 2026-03-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Mystery', 'Mystery'), ('scifi', 'Science Fiction'), ('romance', 'Romance'), ('biography', 'Biography'), ('selfhelp', 'Self Help'), ('business', 'Business'), ('history', 'History')], max_length=20),
        ),
    ]
