# Generated by Django 6.0.2 on 2026-03-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('mystery', 'Mystery'), ('scifi', 'Science Fiction'), ('romance', 'Romance'), ('biography', 'Biography'), ('selfhelp', 'Self Help'), ('business', 'Business'), ('history', 'History')], max_length=20),
        ),
    ]
