# Generated by Django 6.0.2 on 2026-03-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_description_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
