# Generated by Django 6.0.2 on 2026-03-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default='2026-03-04'),
            preserve_default=False,
        ),
    ]
